FROM python:3.11.4-slim-buster


WORKDIR /var/www/vue_course_lifecycle

ENV PYTHONDONTWRITEBYTECODE 1

RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY ./backend /var/www/vue_course_lifecycle/.

# CMD ["python3", "manage.py", "runserver"]